version: "3.8"
services:
  angular:
    build: 
      context: .
      dockerfile: fe.Dockerfile
    ports:
      - "4000:4200"
    volumes:
      - "/app/node_modules"
      - ".:/app"
    networks:
      - ds-management-network

networks:
    ds-management-network:
      external: true
